# Generated by Django 5.0.1 on 2024-01-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nascimento', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=3)),
                ('altura', models.IntegerField()),
                ('imc', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
            ],
        ),
    ]
