# Generated by Django 5.0.1 on 2024-01-08 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_diastreino_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diastreino',
            name='registro',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 8, 3, 12, 58, 827996, tzinfo=datetime.timezone.utc)),
        ),
    ]
