# Generated by Django 5.0.1 on 2024-01-12 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_diastreino_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='diastreino',
            name='foi_bom',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='diastreino',
            name='registro',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 12, 30, 19, 292217)),
        ),
    ]
