# Generated by Django 5.0.1 on 2024-01-27 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0005_pesousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesousuario',
            name='data_registro',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
