# Generated by Django 5.0.1 on 2024-01-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0006_pesousuario_data_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesousuario',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
